export const GENERATE_VIDEO_FROM_PROMPT = 'GENERATE_VIDEO_FROM_PROMPT';
export const SET_AUTH_ERROR_MSG = 'SET_AUTH_ERROR_MSG';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';
export const SET_USER_UPLOADS = 'SET_USER_UPLOADS';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
