export const SET_AUTH_ERROR_MSG = 'SET_AUTH_ERROR_MSG';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
